[package]
name = "usb_ninja_pico"
version = "0.1.0"
edition = "2021"

[dependencies]
rp-pico = "0.8"
cortex-m-rt = "0.7"
panic-halt = "0.2"
usb-device = "0.2"
usbd-hid = "0.7"
usbd-mass-storage = "0.4"
